---
abstract: 'Catmandu module for working with Z3950 data'
author:
  - 'Wouter Willaert <wouterw@inuits.eu>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Z3950
provides:
  Catmandu::Importer::Z3950:
    file: lib/Catmandu/Importer/Z3950.pm
    version: 0
  Catmandu::Z3950:
    file: lib/Catmandu/Z3950.pm
    version: 0.01
requires:
  Catmandu: 0.0302
  Moo: 1.000003
  ZOOM: 1.28
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
